version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "auth_service"
      POSTGRES_SSL_MODE: "disabled"
    ports:
      - "5432:5432"
    volumes:
      - ./app/repository/migrations/:/docker-entrypoint-initdb.d/
    networks:
      - auth_netw

  app:
    image: golang:1.22
    container_name: app
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "pass"
      POSTGRES_NAME: "auth_service"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_SSL_MODE: "disable"
      WEB_SERVER_PORT: 8080
      SECRET: "serverSecret"
      MAILER_USER: "gutrovr@gmail.com"
      MAILER_PASS: "xlil cmik rryn mfmg"
    build: .
    command: make run
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - auth_netw

networks:
  auth_netw:
    driver: host